### PR TITLE
Fix build on recent keycode changes.

### PR DESCRIPTION
**Pull request by return**
This fixes the WebKit build prior to the recent key code changes.

### CODE REVIEW

**Review by waddlesplash — APPROVED** [review]

**Comment by pulkomandy** [comment]
I already have a fix locally, which involves more than that (the handling of modifiers is not correct, they cannot be extracted from the string).

**Comment by return** [comment]
Fair enough, I didn't notice about the key modifiers not being read properly. I only tested whether if the keys can be read directly from https://keycode.info after fixing the build failure.

I'll close this PR as superseded once your patches are merged in.

**Comment by pulkomandy** [comment]
Thanks, sorry for the delay in uploading the changes :)

**Comment by return** [comment]
Superseded by commits [ffd2498](https://github.com/haiku/webkit/commit/ffd2498f9287a8e6cbccb2c57ebe6def719c9b19) and [f6008ec](https://github.com/haiku/webkit/commit/f6008eccc93d07060fb534f8308b311555cc09e7).

**Pull request closed without merging**
